services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
      - ./src/storage:/var/www/html/storage
      - ./src/vendor:/var/www/html/vendor
      - ./src/node_modules:/var/www/html/node_modules
    user: "${UID}:${GID}"  
    networks:
      - laravel_network
    ports:
      - "${PHP_PORT}:9000"
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_REVALIDATE_FREQ=0

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - laravel_network
    ports:
      - "${APP_PORT}:80"

  db:
    image: postgres:latest
    container_name: laravel_postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - laravel_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - laravel_network

volumes:
  pg_data:

networks:
  laravel_network:
